//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Read4Me.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Read4Me.Hotkey open_hide_hk {
            get {
                return ((global::Read4Me.Hotkey)(this["open_hide_hk"]));
            }
            set {
                this["open_hide_hk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Read4Me.Hotkey pause_resume_hk {
            get {
                return ((global::Read4Me.Hotkey)(this["pause_resume_hk"]));
            }
            set {
                this["pause_resume_hk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Read4Me.Hotkey previous_sentence_hk {
            get {
                return ((global::Read4Me.Hotkey)(this["previous_sentence_hk"]));
            }
            set {
                this["previous_sentence_hk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Read4Me.Hotkey next_sentence_hk {
            get {
                return ((global::Read4Me.Hotkey)(this["next_sentence_hk"]));
            }
            set {
                this["next_sentence_hk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Read4Me.SpeekLangHotkey speek_lang_hk {
            get {
                return ((global::Read4Me.SpeekLangHotkey)(this["speek_lang_hk"]));
            }
            set {
                this["speek_lang_hk"] = value;
            }
        }
    }
}
